# Generated by Django 3.2.15 on 2022-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visit_places',
            field=models.ManyToManyField(blank=True, related_name='visit_users', to='accounts.Place'),
        ),
    ]
