# Generated by Django 3.2.15 on 2022-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220906_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category_group_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='distance',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='address_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='category_group_name',
            field=models.CharField(max_length=100),
        ),
    ]
