# Generated by Django 3.2.15 on 2022-09-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220911_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='x',
        ),
        migrations.RemoveField(
            model_name='place',
            name='y',
        ),
    ]
